apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uqncm5ah6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uqncm5ah6-java-quarkus-gitops